export const CONTACT_ME_EMAIL_REQUEST = 'CONTACT_ME_EMAIL_REQUEST';
export const CONTACT_ME_EMAIL_CLEAR = "CONTACT_ME_EMAIL_CLEAR";
export const CONTACT_ME_EMAIL_SUCCESS = 'CONTACT_ME_EMAIL_SUCCESS';
export const CONTACT_ME_EMAIL_FAILURE = 'CONTACT_ME_EMAIL_FAILURE';