export const CONTACT_REQUEST = 'VIEW_CONTACTS_REQUEST';
export const CONTACT_SUCCESS = 'VIEW_CONTACTS_SUCCESS';
export const CONTACT_FAILURE = 'VIEW_CONTACTS_FAILURE';
export const CONTACT_CHECKED = 'VIEW_CONTACTS_CHECKED';
export const CONTACT_CHECKED_ALL = 'VIEW_CONTACTS_CHECKED_ALL';