export const VIEW_CONTACTS_REQUEST = 'VIEW_CONTACTS_REQUEST';
export const VIEW_CONTACTS_SUCCESS = 'VIEW_CONTACTS_SUCCESS';
export const VIEW_CONTACTS_FAILURE = 'VIEW_CONTACTS_FAILURE';
export const VIEW_CONTACTS_CHECKED = 'VIEW_CONTACTS_CHECKED';
export const VIEW_CONTACTS_CHECKED_ALL = 'VIEW_CONTACTS_CHECKED_ALL';